[project]
name = "deepagents-questionpaper-setter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "deepagents>=0.7.5",
    "langchain-google-genai>=4.3.2",
    "langgraph-cli[inmem]>=0.4.31",
    "python-dotenv>=1.2.2",
    "tavily>=1.1.0",
]
